### ISSUE TITLE
Add action panel

### ISSUE THREAD

**Issue by haakonjacobsen** [AndreasWintherMoen/learning-by-gaming#11]
![Screenshot 2023-03-08 at 13 59 39](https://user-images.githubusercontent.com/15661593/223719492-29fb1594-c1bd-4767-80c9-65434be0f812.png)

**Comment by AndreasWintherMoen** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/4c1e2605-d05e-40b5-8ef2-2652c4cc214c-34ecf193-27bc-400d-b0e0-397282d0b9a4-v1.png?transparent=1&palette=1&width=246)
