### ISSUE TITLE
Fix hit detection on 0 amplitude

### ISSUE THREAD

**Issue by haakonjacobsen** [AndreasWintherMoen/learning-by-gaming#118]
On lvl 4 when the amplitude should be 0, the hit detection does not work. 

![Screenshot 2023-04-08 at 18 54 05](https://user-images.githubusercontent.com/15661593/230733435-978e494c-b5bf-4fea-af23-36d65593b6b2.png)

**Comment by AndreasWintherMoen** [comment]
Already created an issue for this. See #113
