### ISSUE TITLE
Persist levels to localStorage

### ISSUE THREAD

**Issue by haakonjacobsen** [AndreasWintherMoen/learning-by-gaming#40]
Add redux persist to save redux state to local storage automatically

**Comment by AndreasWintherMoen** [comment]
I don't think we need to persist the entire redux state. It's enough to store info about which levels the user has unlocked and the score they have for each. Then we can regenerate the redux state with that information.

**Comment by AndreasWintherMoen** [comment]
Note that this issue also includes loading level info back from localStorage.
